version: '3'

services:
  mysql:
    image: mysql:8.2.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: FileStorageServiceDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped

networks:
  storage-app:
    driver: bridge