spring:
  application:
    name: FileStorageService
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    sas-token: ${AZURE_STORAGE_SAS_TOKEN}
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}


